// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG8VctGA1s8K0avrzRHHhSpX7qcc8W8fI',
    appId: '1:1032034473339:web:658586f49f750611e799de',
    messagingSenderId: '1032034473339',
    projectId: 'isl-translator-493212',
    authDomain: 'isl-translator-493212.firebaseapp.com',
    storageBucket: 'isl-translator-493212.firebasestorage.app',
    measurementId: 'G-QZ5YDLZCSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA60kSquPmr57BBp2ByE4iWM0cEbm_sqmU',
    appId: '1:1032034473339:android:8fb80ac2a7eaf4e6e799de',
    messagingSenderId: '1032034473339',
    projectId: 'isl-translator-493212',
    storageBucket: 'isl-translator-493212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZZTsBAjSnFelZB7Iahl2qjv17AxJ-KKM',
    appId: '1:1032034473339:ios:405c4d27051519a4e799de',
    messagingSenderId: '1032034473339',
    projectId: 'isl-translator-493212',
    storageBucket: 'isl-translator-493212.firebasestorage.app',
    iosBundleId: 'com.example.islTranslator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZZTsBAjSnFelZB7Iahl2qjv17AxJ-KKM',
    appId: '1:1032034473339:ios:405c4d27051519a4e799de',
    messagingSenderId: '1032034473339',
    projectId: 'isl-translator-493212',
    storageBucket: 'isl-translator-493212.firebasestorage.app',
    iosBundleId: 'com.example.islTranslator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG8VctGA1s8K0avrzRHHhSpX7qcc8W8fI',
    appId: '1:1032034473339:web:d5b5b06bf88595c4e799de',
    messagingSenderId: '1032034473339',
    projectId: 'isl-translator-493212',
    authDomain: 'isl-translator-493212.firebaseapp.com',
    storageBucket: 'isl-translator-493212.firebasestorage.app',
    measurementId: 'G-G4NNE8HE87',
  );
}
